#!/bin/bash
# Simple test runner using Docker - no local Poetry needed!
# Usage: ./run_tests.sh [unit|integration|all|e2e] [--no-cov]
#
# Coverage reports are generated by default:
# - Terminal summary with missing lines
# - HTML report: backend/htmlcov/index.html
# - XML report: backend/coverage.xml

set -e

TEST_TYPE="${1:-all}"
NO_COV="${2:-}"

# Coverage options
COV_OPTS="--cov=backend.src --cov-report=html --cov-report=term-missing --cov-report=xml --cov-branch"

# Remove coverage options if --no-cov flag is set
if [ "$NO_COV" = "--no-cov" ] || [ "$1" = "--no-cov" ]; then
  COV_OPTS=""
  # Shift arguments if --no-cov was first
  if [ "$1" = "--no-cov" ]; then
    TEST_TYPE="${2:-all}"
  fi
fi

case "$TEST_TYPE" in
  unit)
    echo "🧪 Running unit tests with Docker..."
    if [ -n "$COV_OPTS" ]; then
      echo "📊 Coverage report will be generated"
    fi
    docker compose exec backend poetry run pytest tests/unit -v -m unit $COV_OPTS
    if [ -n "$COV_OPTS" ]; then
      echo ""
      echo "📈 Coverage report: backend/htmlcov/index.html"
    fi
    ;;
  integration)
    echo "🧪 Running integration tests with Docker..."
    echo "📊 Testing: Auth API, Tasks API, Checklists API"
    if [ -n "$COV_OPTS" ]; then
      echo "📊 Coverage report will be generated"
    fi
    docker compose exec backend poetry run pytest tests/integration -v -m integration $COV_OPTS
    echo ""
    echo "✅ Integration tests complete! All API endpoints verified."
    if [ -n "$COV_OPTS" ]; then
      echo "📈 Coverage report: backend/htmlcov/index.html"
    fi
    ;;
  all)
    echo "🧪 Running all tests (unit + integration) with Docker..."
    if [ -n "$COV_OPTS" ]; then
      echo "📊 Coverage report will be generated"
    fi
    docker compose exec backend poetry run pytest tests/unit tests/integration -v $COV_OPTS
    if [ -n "$COV_OPTS" ]; then
      echo ""
      echo "📈 Coverage report: backend/htmlcov/index.html"
      echo "   Open it in your browser to see detailed coverage!"
    fi
    ;;
  e2e)
    echo "🧪 Running E2E tests with Docker..."
    echo "⚠️  Note: E2E tests require frontend and backend services to be running"
    echo "⚠️  Make sure you've started: docker compose up backend db redis"
    echo "⚠️  And frontend: cd frontend && npm run dev"
    # E2E tests typically don't need coverage
    docker compose exec backend poetry run pytest tests/e2e -v -m e2e -o "ignore="
    ;;
  *)
    echo "Usage: $0 [unit|integration|all|e2e] [--no-cov]"
    echo ""
    echo "  unit        - Run only unit tests"
    echo "  integration - Run only integration tests"
    echo "  all         - Run unit + integration tests (default)"
    echo "  e2e         - Run E2E tests (requires running services)"
    echo ""
    echo "Options:"
    echo "  --no-cov    - Skip coverage report generation"
    echo ""
    echo "Coverage reports:"
    echo "  - Terminal: Summary with missing lines"
    echo "  - HTML: backend/htmlcov/index.html (open in browser)"
    echo "  - XML: backend/coverage.xml (for CI/CD tools)"
    echo ""
    echo "This script uses Docker - no local Poetry installation needed!"
    exit 1
    ;;
esac

